#####
#
# serverspec/tasks/main.yml
#
#####

---
- name: reload .bash_profile
  shell: bash -lc "source /home/centos/.bash_profile"

- name: rbenv install -v 2.6.4
  shell: bash -lc "/home/centos/.rbenv/bin/rbenv install -v 2.6.4"
  ignore_errors: yes

- name: rbenv rehash
  shell: bash -lc "/home/centos/.rbenv/bin/rbenv rehash"
  ignore_errors: yes

- name: rbenv global 2.6.4
  shell: bash -lc "/home/centos/.rbenv/bin/rbenv global 2.6.4"
  ignore_errors: yes

- name: gem update --system
  shell: bash -lc "gem update --system"
  ignore_errors: yes

- name: install rake
  shell: bash -lc "gem install rake"
  ignore_errors: yes

- name: install serverspec
  shell: bash -lc "gem install serverspec"
  ignore_errors: yes

#- name: install serverspec
#  gem:
#    name: "{{ item }}"
#    state: present
#  with_items:
#    - rake
#    - serverspec

- name: serverspec init configs
  copy:
    src: ../files/
    dest: /home/centos/
    owner: centos
    group: centos
    mode: '0644'

- name: set spec file
  template:
    src: web_spec.rb.j2
    dest: /home/centos/spec/localhost/web_spec.rb
    owner: centos
    group: centos
    mode: '0644'
