#####
#
# serverspec/tasks/main.yml
#
#####

---
- name: Install ruby
  shell: rbenv install -v 2.6.4
  ignore_errors: true

- name: set ruby version for global
  shell: rbenv global 2.6.4
  ignore_errors: true

- name: install serverspec
  gem:
    name: "{{ item }}"
    state: present
  with_items:
    - rake
    - serverspec
