#####
#
# common/tasks/main.yml
#
#####

---
- name: Install some packages
  package:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - bzip2
    - gcc
    - openssl-devel
    - readline-devel
    - zlib-devel

- name: git clone of rbenv
  git:
    repo: 'https://github.com/sstephenson/rbenv.git'
    dest: /home/centos/.rbenv

- name: git clone of ruby-build
  git:
    repo: 'https://github.com/sstephenson/ruby-build.git'
    dest: /home/centos/.rbenv/plugins/ruby-build

- name: change user and group for .rbenc directory
  file:
    path: /home/centos/.rbenv
    state: directory
    owner: centos
    group: centos
    recurse: yes

- name: Add file path to bash_profile
  lineinfile:
    path: /home/centos/.bash_profile
    line: export PATH="$HOME/.rbenv/bin:$PATH"

- name: Add rbenv init to bash_profile
  lineinfile:
    path: /home/centos/.bash_profile
    line: eval "$(rbenv init -)"
